language: c++
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      compiler:
        - clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        - DO_DEPLOY="n" # TODO: set this to "y" to enable deploys
    - os: linux
      compiler:
        - clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.9"
        - DO_DEPLOY="n"
    - os: linux
      compiler:
        - clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-4.0"
        - DO_DEPLOY="n"
    - os: linux
      compiler:
        - clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-5.0"
        - DO_DEPLOY="n"


before_install:
  - eval $MATRIX_EVAL
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS='-Wall -Wextra -Wpedantic -std=c++1z'
  - make -j8
  - cd ..
  - for file in tests/cpp/*;do clang++ -c -emit-llvm -o $file.bc $file;opt -O3 $file.bc > $file.opt.bc;llvm-dis $file.opt.bc;done
# deploy stuff
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: icecream95/icecream95.github.io
  target_branch: scratch-llvm
  on:
    branch: master
    condition: $DO_DEPLOY = "y"
